jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@1.3.0
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify:
              job_type: deployment
              token_name:
                default: circleci
                description: The name of environment variable containing CircleCI API Token. Required for all projects.
                type: string